from __future__ import annotations


def g(
    question: str,
    status: str,
    operation: str | None = None,
    entity: str | None = None,
    metric: str | None = None,
    group_by: tuple[str, ...] = (),
    filters: dict[str, object] | None = None,
    limit: int | None = None,
    columns: tuple[str, ...] = (),
) -> dict[str, object]:
    return {
        "question": question,
        "status": status,
        "operation": operation,
        "entity": entity,
        "metric": metric,
        "group_by": list(group_by),
        "filters": filters or {},
        "limit": limit,
        "columns": list(columns),
    }


CORE_BATTER_METRICS = [
    "batting_strike_rate",
    "runs_scored",
    "batting_average",
    "batter_dot_ball_percentage",
    "boundary_percentage",
]
CORE_BOWLER_METRICS = [
    "economy_rate",
    "bowling_average",
    "wickets_taken",
    "bowler_dot_ball_percentage",
    "boundary_percentage",
]


GOLDEN_FACTUAL_CHAT_CASES = [
    g("What is Virat Kohli's strike rate in ODIs?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Virat Kohli"}, columns=("batter", "batting_strike_rate", "balls")),
    g("What is Virat Kohli's dot-ball percentage against spin since 2022?", "supported", "aggregate", "batter", "batter_dot_ball_percentage", ("batter",), {"batter": "Virat Kohli", "bowling_style": "spin", "year_mode": "after", "years": [2022]}, columns=("batter", "batter_dot_ball_percentage", "balls")),
    g("How many runs has Rohit Sharma scored?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"batter": "Rohit Sharma"}, columns=("batter", "runs_scored")),
    g("How many balls has Shreyas Iyer faced?", "supported", "aggregate", "batter", "balls_faced", ("batter",), {"batter": "Shreyas Iyer"}, columns=("batter", "balls_faced")),
    g("What is Jasprit Bumrah's economy rate in death overs?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"bowler": "Jasprit Bumrah", "phase": "death"}, columns=("bowler", "economy_rate", "legal_balls")),
    g("How many wickets has Pat Cummins taken in the powerplay?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), {"bowler": "Pat Cummins", "phase": "powerplay"}, columns=("bowler", "wickets_taken")),
    g("What is Bumrah's yorker percentage at the death?", "supported", "aggregate", "bowler", "yorker_percentage", ("bowler",), {"bowler": "Jasprit Bumrah", "phase": "death"}, columns=("bowler", "yorker_percentage", "legal_balls")),
    g("How many yorkers has Mitchell Starc bowled?", "supported", "aggregate", "bowler", "yorker_count", ("bowler",), {"bowler": "Mitchell Starc"}, columns=("bowler", "yorker_count")),
    g("What is Hardik Pandya's boundary percentage against pace?", "supported", "aggregate", "batter", "boundary_percentage", ("batter",), {"batter": "Hardik Pandya", "bowling_style": "pace"}, columns=("batter", "boundary_percentage", "balls")),
    g("What is Shreyas Iyer's false-shot percentage against short balls after 2023?", "supported", "aggregate", "batter", "false_shot_percentage", ("batter",), {"batter": "Shreyas Iyer", "length": "SHORT", "year_mode": "after", "years": [2023]}, columns=("batter", "false_shot_percentage", "balls")),
    g("Who has scored the most runs?", "supported", "aggregate", "batter", "runs_scored", ("batter",), columns=("batter", "runs_scored")),
    g("Which batter has the highest strike rate?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), columns=("batter", "batting_strike_rate")),
    g("Which batter has the lowest dot-ball percentage?", "supported", "aggregate", "batter", "batter_dot_ball_percentage", ("batter",), columns=("batter", "batter_dot_ball_percentage")),
    g("Which bowler has the best economy rate?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), columns=("bowler", "economy_rate")),
    g("Which bowler has taken the most wickets?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), columns=("bowler", "wickets_taken")),
    g("Which bowler has the highest yorker percentage?", "supported", "aggregate", "bowler", "yorker_percentage", ("bowler",), columns=("bowler", "yorker_percentage")),
    g("Which bowler generates the most false shots per over?", "supported", "aggregate", "bowler", "false_shots_per_over", ("bowler",), columns=("bowler", "false_shots_per_over")),
    g("Which bowler concedes the fewest boundaries per 100 balls?", "supported", "aggregate", "bowler", "boundary_rate_per_100_balls", ("bowler",), columns=("bowler", "boundary_rate_per_100_balls")),
    g("Which batter has the highest false-shot percentage against spin?", "supported", "aggregate", "batter", "false_shot_percentage", ("batter",), {"bowling_style": "spin"}, columns=("batter", "false_shot_percentage")),
    g("Which batter is hardest to bowl dot balls to?", "supported", "aggregate", "batter", "batter_dot_ball_percentage", ("batter",), columns=("batter", "batter_dot_ball_percentage")),
    g("Show the top five batters by runs scored.", "supported", "aggregate", "batter", "runs_scored", ("batter",), limit=5, columns=("batter", "runs_scored")),
    g("Show top 5 bowlers by economy rate.", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), limit=5, columns=("bowler", "economy_rate")),
    g("Who are the bottom five batters by strike rate?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), limit=5, columns=("batter", "batting_strike_rate")),
    g("List the top ten bowlers by wickets taken.", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), limit=10, columns=("bowler", "wickets_taken")),
    g("Which five batters have faced the most balls?", "supported", "aggregate", "batter", "balls_faced", ("batter",), limit=5, columns=("batter", "balls_faced")),
    g("Give me the top five bowlers by yorker percentage.", "supported", "aggregate", "bowler", "yorker_percentage", ("bowler",), limit=5, columns=("bowler", "yorker_percentage")),
    g("Which bowlers concede the fewest boundaries per 100 balls, minimum 120 legal balls?", "supported", "aggregate", "bowler", "boundary_rate_per_100_balls", ("bowler",), columns=("bowler", "boundary_rate_per_100_balls", "legal_balls")),
    g("Show the top five bowlers by wicket opportunity rate.", "supported", "aggregate", "bowler", "wicket_opportunity_rate", ("bowler",), limit=5, columns=("bowler", "wicket_opportunity_rate")),
    g("Who has the worst economy rate in the powerplay?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"phase": "powerplay"}, columns=("bowler", "economy_rate")),
    g("Which batter has the best strike rate since 2023?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"year_mode": "after", "years": [2023]}, columns=("batter", "batting_strike_rate")),
    g("Who has dismissed David Miller most often?", "supported", "matchup", "bowler", "wickets_taken", ("bowler",), {"batter": "David Miller"}, columns=("bowler", "wickets", "sample_size")),
    g("Which bowler controls Virat Kohli best?", "supported", "matchup", "bowler", "bowler_dot_ball_percentage", ("bowler",), {"batter": "Virat Kohli"}, columns=("bowler", "bowler_dot_percentage", "sample_size")),
    g("Which batter-bowler matchup has produced the most wickets?", "supported", "matchup", "matchup", "wickets_taken", ("matchup",), columns=("batter", "bowler", "wickets", "sample_size")),
    g("Which matchup produces the highest false-shot percentage?", "supported", "matchup", "matchup", "false_shot_percentage", ("matchup",), columns=("batter", "bowler", "false_shot_percentage", "sample_size")),
    g("Which matchup has produced the most wickets in death overs?", "supported", "matchup", "matchup", "wickets_taken", ("matchup",), {"phase": "death"}, columns=("batter", "bowler", "wickets", "sample_size")),
    g("How does Heinrich Klaasen perform against wrist spin?", "supported", "matchup", "batter", "batting_strike_rate", ("batter",), {"batter": "Heinrich Klaasen", "bowling_style": "wrist_spin"}, columns=("batter", "bowling_style", "strike_rate")),
    g("Which batter dominates left-arm pace?", "supported", "matchup", "batter", "batting_strike_rate", ("batter",), {"bowling_style": "left_arm_pace"}, columns=("batter", "bowling_style", "strike_rate")),
    g("Which bowler is most successful against finishers?", "supported", "matchup", "bowler", "wickets_taken", ("bowler",), {"phase": "death"}, columns=("bowler", "wickets", "sample_size")),
    g("Which bowler has the best death-over economy?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"phase": "death"}, columns=("bowler", "economy_rate")),
    g("Who scores most runs in the powerplay?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"phase": "powerplay"}, columns=("batter", "runs_scored")),
    g("Which batter has the highest strike rate in death overs?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"phase": "death"}, columns=("batter", "batting_strike_rate")),
    g("Which bowler takes most wickets in middle overs?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), {"phase": "middle"}, columns=("bowler", "wickets_taken")),
    g("What is Virat Kohli's strike rate in the powerplay?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Virat Kohli", "phase": "powerplay"}, columns=("batter", "batting_strike_rate")),
    g("What is Rohit Sharma's dot-ball percentage in middle overs?", "supported", "aggregate", "batter", "batter_dot_ball_percentage", ("batter",), {"batter": "Rohit Sharma", "phase": "middle"}, columns=("batter", "batter_dot_ball_percentage")),
    g("Which batter has scored the most runs since 2022?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"year_mode": "after", "years": [2022]}, columns=("batter", "runs_scored")),
    g("Which bowler has the best economy since 2023?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"year_mode": "after", "years": [2023]}, columns=("bowler", "economy_rate")),
    g("Who has the highest strike rate in 2023?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"years": [2023]}, columns=("batter", "batting_strike_rate")),
    g("Which bowler took the most wickets in 2023?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), {"years": [2023]}, columns=("bowler", "wickets_taken")),
    g("Where does Hardik Pandya score most runs?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"batter": "Hardik Pandya"}, columns=("batter", "runs_scored")),
    g("Which shot does Hardik Pandya score most from?", "supported", "aggregate", "batter", "runs_scored", ("shot_type",), {"batter": "Hardik Pandya"}, columns=("shot_type", "runs_scored")),
    g("What shot does Jos Buttler score most runs from?", "supported", "aggregate", "batter", "runs_scored", ("shot_type",), {"batter": "Jos Buttler"}, columns=("shot_type", "runs_scored")),
    g("Which field zone does Virat Kohli score most runs in?", "supported", "aggregate", "batter", "runs_scored", ("field_zone",), {"batter": "Virat Kohli"}, columns=("field_zone", "runs_scored")),
    g("Which scoring zone gives Rohit Sharma the best strike rate?", "supported", "aggregate", "batter", "batting_strike_rate", ("field_zone",), {"batter": "Rohit Sharma"}, columns=("field_zone", "batting_strike_rate")),
    g("Which line generates the most dot balls against Virat Kohli?", "supported", "aggregate", "bowler", "bowler_dot_ball_percentage", ("line",), {"batter": "Virat Kohli"}, columns=("line", "bowler_dot_ball_percentage")),
    g("Which length dismisses David Miller most often?", "supported", "aggregate", "bowler", "wickets_taken", ("length",), {"batter": "David Miller"}, columns=("length", "wickets_taken")),
    g("Which length produces the most false shots against Shreyas Iyer?", "supported", "aggregate", "bowler", "false_shot_percentage", ("length",), {"batter": "Shreyas Iyer"}, columns=("length", "false_shot_percentage")),
    g("Which line is most economical for Bumrah?", "supported", "aggregate", "bowler", "economy_rate", ("line",), {"bowler": "Jasprit Bumrah"}, columns=("line", "economy_rate")),
    g("Which length does Starc bowl most often?", "supported", "aggregate", "bowler", "legal_balls", ("length",), columns=("length", "legal_balls")),
    g("Against which bowling type does Heinrich Klaasen score fastest?", "supported", "aggregate", "batter", "batting_strike_rate", ("bowling_style",), {"batter": "Heinrich Klaasen"}, columns=("bowling_style", "batting_strike_rate")),
    g("Which bowler performs significantly better against left-handers than right-handers?", "supported", "split_compare", "bowler", "economy_rate", ("bowler",), columns=("bowler", "difference", "rank_value")),
    g("Which batter dominates wrist spin but struggles against finger spin?", "supported", "split_compare", "batter", "batting_strike_rate", ("batter",), columns=("batter", "difference", "rank_value")),
    g("Which bowler has the biggest difference between powerplay and death-over economy?", "supported", "split_compare", "bowler", "economy_rate", ("bowler",), columns=("bowler", "difference", "rank_value")),
    g("Which batter improves their strike rate the most after facing 20 balls?", "supported", "split_compare", "batter", "batting_strike_rate", ("batter",), columns=("batter", "difference", "rank_value")),
    g("Which team accelerates most effectively between overs 15 and 20?", "supported", "split_compare", "team", "run_rate", ("team",), {"over_range": [15, 20]}, columns=("team", "difference", "rank_value")),
    g("Does Shreyas Iyer struggle against short balls after 2023?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Shreyas Iyer", "length": "SHORT", "year_mode": "after", "years": [2023]}, columns=("batter", "batting_strike_rate")),
    g("Does Rohit Sharma struggle against left-arm pace?", "supported", "matchup", "batter", "batting_strike_rate", ("batter",), {"batter": "Rohit Sharma", "bowling_style": "left_arm_pace"}, columns=("batter", "strike_rate")),
    g("Which bowler bowls the highest percentage of yorkers at the death?", "supported", "aggregate", "bowler", "yorker_percentage", ("bowler",), {"phase": "death"}, columns=("bowler", "yorker_percentage")),
    g("What is Bumrah's false shots per over against right-handers?", "supported", "aggregate", "bowler", "false_shots_per_over", ("bowler",), {"bowler": "Jasprit Bumrah", "batter_hand": "RHB"}, columns=("bowler", "false_shots_per_over")),
    g("Which batter has the best boundary percentage against short balls?", "supported", "aggregate", "batter", "boundary_percentage", ("batter",), {"length": "SHORT"}, columns=("batter", "boundary_percentage")),
    g("Which bowler has the highest bowler dot ball percentage?", "supported", "aggregate", "bowler", "bowler_dot_ball_percentage", ("bowler",), columns=("bowler", "bowler_dot_ball_percentage")),
    g("What is Rohit Sharma's batting strike rate against leg spin?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Rohit Sharma", "bowling_style": "leg_spin"}, columns=("batter", "batting_strike_rate")),
    g("What is Virat Kohli's dismissal count against spin?", "supported", "aggregate", "batter", "dismissals", ("batter",), {"batter": "Virat Kohli", "bowling_style": "spin"}, columns=("batter", "dismissals")),
    g("Which batter has the highest strike rate against good length balls?", "supported", "aggregate", "batter", "batting_strike_rate", ("length",), {"length": "GOOD_LENGTH"}, columns=("length", "batting_strike_rate")),
    g("Which line does Bumrah bowl most in the death?", "supported", "aggregate", "bowler", "legal_balls", ("line",), {"bowler": "Jasprit Bumrah", "phase": "death"}, columns=("line", "legal_balls")),
    g("Compare Virat Kohli at number 3 vs opening in ODIs.", "supported", "batting_position_compare"),
    g("Where does Hardik Pandya score the most and on which shots?", "supported", "batting_profile"),
    g("Compare Virat Kohli and Steven Smith in ODIs.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Virat Kohli", "Steven Smith"], "comparison_metrics": CORE_BATTER_METRICS}, columns=("player", "batting_strike_rate")),
    g("Compare Starc and Bumrah at the death.", "supported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": CORE_BOWLER_METRICS, "phase": "death"}, columns=("player", "economy_rate")),
    g("Who scores faster, Rohit Sharma or Virat Kohli?", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Virat Kohli"], "comparison_metrics": ["batting_strike_rate"]}, columns=("player", "batting_strike_rate")),
    g("Compare Jasprit Bumrah and Mitchell Starc by economy rate.", "supported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": ["economy_rate"]}, columns=("player", "economy_rate")),
    g("Compare Shreyas Iyer and KL Rahul against spin.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Shreyas Iyer", "KL Rahul"], "comparison_metrics": CORE_BATTER_METRICS, "bowling_style": "spin"}, columns=("player", "batting_strike_rate")),
    g("What was India's total in the 2011 World Cup final?", "supported", "match_fact", "team", "runs_scored", ("team",), {"competition": "ICC Cricket World Cup", "match_stage": "final", "fact_type": "team_total", "team": "India", "years": [2011]}, columns=("team", "runs")),
    g("Who won the 2011 World Cup final?", "supported", "match_fact", "team", "runs_scored", ("team",), {"competition": "ICC Cricket World Cup", "match_stage": "final", "fact_type": "winner", "years": [2011]}, columns=("team", "runs")),
    g("Build a bowling plan against David Miller.", "supported", "tactical_recommendation", "batter", "runs_scored", columns=("bucket", "dot_percentage", "false_shot_percentage")),
    g("Predict who will win if India chase 280.", "unsupported", "predictive_analysis", "team", "runs_scored"),
    g("Which team loses momentum most frequently after the powerplay?", "unsupported", "event_window", "team", "runs_scored"),
    g("Who was Player of the Match in the 2011 World Cup final?", "insufficient_evidence", "aggregate", "batter", "runs_scored"),
    g("Who took most catches in the 2023 World Cup?", "insufficient_evidence", "aggregate", "batter", "runs_scored"),
    g("Who has the best average against Australia?", "supported", "aggregate", "batter", "batting_average", ("batter",), {"opposition": "Australia"}, columns=("batter", "batting_average")),
    g("What is Kohli's record against Pakistan?", "unsupported", "aggregate", "batter", "runs_scored"),
    g("Show opposition-wise performance of James Anderson.", "unsupported", "aggregate", "batter", "runs_scored"),
    g("Which team wins most often after losing early wickets?", "unsupported", "predictive_analysis", "team", "wickets_taken"),
    g("Which batter should be targeted with short-ball tactics?", "unsupported", "tactical_recommendation", "batter", "runs_scored"),
    g("Which team scores fastest in the powerplay?", "unsupported", "aggregate", "team", "batting_strike_rate"),
    g("Which team has the best economy rate?", "unsupported", "aggregate", "bowler", "economy_rate", ("team",)),
    g("Which batting team scores the most runs?", "unsupported", "aggregate", "team", "runs_scored"),
    g("Who has the most wickets at Melbourne Cricket Ground?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), {"venue": "Melbourne Cricket Ground"}, columns=("bowler", "wickets_taken")),
    g("Against which line does Shreyas Iyer score fastest?", "unsupported", "aggregate", "bowler", "batting_strike_rate"),
    g("Which bowler has the most legal balls?", "supported", "aggregate", "bowler", "legal_balls", ("bowler",), columns=("bowler", "legal_balls")),
    g("Which bowler has bowled the most overs?", "supported", "aggregate", "bowler", "overs_bowled", ("bowler",), columns=("bowler", "overs_bowled", "legal_balls")),
    g("What is Mitchell Starc's bowler dot ball percentage?", "supported", "aggregate", "bowler", "bowler_dot_ball_percentage", ("bowler",), {"bowler": "Mitchell Starc"}, columns=("bowler", "bowler_dot_ball_percentage")),
    g("How many dot balls has Virat Kohli faced?", "supported", "aggregate", "batter", "dot_balls", ("batter",), {"batter": "Virat Kohli"}, columns=("batter", "dot_balls")),
    g("Compare Kohli and Rohit against Australia.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Virat Kohli"], "comparison_metrics": CORE_BATTER_METRICS, "opposition": "Australia"}, columns=("player", "batting_strike_rate")),
    g("Compare Rohit Sharma and Virat Kohli versus Pakistan.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Virat Kohli"], "comparison_metrics": CORE_BATTER_METRICS, "opposition": "Pakistan"}, columns=("player", "batting_strike_rate")),
    g("Who scores faster, KL Rahul or Shreyas Iyer against spin?", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Shreyas Iyer", "KL Rahul"], "comparison_metrics": ["batting_strike_rate"], "bowling_style": "spin"}, columns=("player", "batting_strike_rate")),
    g("Compare Hardik Pandya and Ravindra Jadeja in death overs.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Hardik Pandya", "Ravindra Jadeja"], "comparison_metrics": CORE_BATTER_METRICS, "phase": "death"}, columns=("player", "batting_strike_rate")),
    g("Compare Steve Smith and Virat Kohli against pace.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Virat Kohli", "Steven Smith"], "comparison_metrics": CORE_BATTER_METRICS, "bowling_style": "pace"}, columns=("player", "batting_strike_rate")),
    g("Compare Buttler and Maxwell by strike rate.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Glenn Maxwell", "Jos Buttler"], "comparison_metrics": ["batting_strike_rate"]}, columns=("player", "batting_strike_rate")),
    g("How do Bumrah and Starc compare on economy?", "supported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": ["economy_rate"]}, columns=("player", "economy_rate")),
    g("Who has the better death-over economy, Bumrah or Starc?", "supported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": ["economy_rate"], "phase": "death"}, columns=("player", "economy_rate")),
    g("How do Starc and Bumrah compare on economy and wicket rate at the death?", "supported", "player_compare", "bowler", "wickets_per_over", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": ["wickets_per_over", "economy_rate"], "phase": "death"}, columns=("player", "wickets_per_over", "economy_rate")),
    g("Compare Rabada and Starc against India.", "supported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Mitchell Starc", "Kagiso Rabada"], "comparison_metrics": CORE_BOWLER_METRICS, "opposition": "India"}, columns=("player", "economy_rate")),
    g("What is Kohli's strike rate against Australia?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Virat Kohli", "opposition": "Australia"}, columns=("batter", "batting_strike_rate")),
    g("What is Rohit Sharma's strike rate versus Pakistan?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Rohit Sharma", "opposition": "Pakistan"}, columns=("batter", "batting_strike_rate")),
    g("How many runs has Virat Kohli scored against England?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"batter": "Virat Kohli", "opposition": "England"}, columns=("batter", "runs_scored")),
    g("What is Bumrah's economy against Australia?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"bowler": "Jasprit Bumrah", "opposition": "Australia"}, columns=("bowler", "economy_rate")),
    g("How many wickets has Starc taken against India?", "supported", "aggregate", "bowler", "wickets_taken", ("bowler",), {"bowler": "Mitchell Starc", "opposition": "India"}, columns=("bowler", "wickets_taken")),
    g("What is Rabada's dot-ball percentage versus Australia?", "supported", "aggregate", "bowler", "bowler_dot_ball_percentage", ("bowler",), {"bowler": "Kagiso Rabada", "opposition": "Australia"}, columns=("bowler", "bowler_dot_ball_percentage")),
    g("Which batter scores fastest against South Africa?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"opposition": "South Africa"}, columns=("batter", "batting_strike_rate")),
    g("Which bowler has the best economy against India?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"opposition": "India"}, columns=("bowler", "economy_rate")),
    g("What is Hardik Pandya's boundary percentage vs England?", "supported", "aggregate", "batter", "boundary_percentage", ("batter",), {"batter": "Hardik Pandya", "opposition": "England"}, columns=("batter", "boundary_percentage")),
    g("What is Pat Cummins' economy versus New Zealand?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"bowler": "Pat Cummins", "opposition": "New Zealand"}, columns=("bowler", "economy_rate")),
    g("What is Bumrah's economy at Wankhede?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"bowler": "Jasprit Bumrah", "venue": "Wankhede Stadium, Mumbai"}, columns=("bowler", "economy_rate")),
    g("How many runs has Virat Kohli scored at Wankhede?", "supported", "aggregate", "batter", "runs_scored", ("batter",), {"batter": "Virat Kohli", "venue": "Wankhede Stadium, Mumbai"}, columns=("batter", "runs_scored")),
    g("What is Rohit Sharma's strike rate at Lord's?", "supported", "aggregate", "batter", "batting_strike_rate", ("batter",), {"batter": "Rohit Sharma", "venue": "Lord's, London"}, columns=("batter", "batting_strike_rate")),
    g("What is Starc's economy at the MCG?", "supported", "aggregate", "bowler", "economy_rate", ("bowler",), {"bowler": "Mitchell Starc", "venue": "Melbourne Cricket Ground"}, columns=("bowler", "economy_rate")),
    g("Show Kohli's strike rate by venue.", "supported", "aggregate", "batter", "batting_strike_rate", ("venue",), {"batter": "Virat Kohli"}, columns=("venue", "batting_strike_rate")),
    g("Which venue has Bumrah's best economy?", "supported", "aggregate", "bowler", "economy_rate", ("venue",), {"bowler": "Jasprit Bumrah"}, columns=("venue", "economy_rate")),
    g("Where has Hardik Pandya scored most runs by venue?", "supported", "aggregate", "batter", "runs_scored", ("venue",), {"batter": "Hardik Pandya"}, columns=("venue", "runs_scored")),
    g("Which ground has Starc taken the most wickets at?", "supported", "aggregate", "bowler", "wickets_taken", ("venue",), {"bowler": "Mitchell Starc"}, columns=("venue", "wickets_taken")),
    g("What is Kohli's dot-ball percentage at Wankhede?", "supported", "aggregate", "batter", "batter_dot_ball_percentage", ("batter",), {"batter": "Virat Kohli", "venue": "Wankhede Stadium, Mumbai"}, columns=("batter", "batter_dot_ball_percentage")),
    g("What is Bumrah's yorker percentage at Wankhede?", "supported", "aggregate", "bowler", "yorker_percentage", ("bowler",), {"bowler": "Jasprit Bumrah", "venue": "Wankhede Stadium, Mumbai"}, columns=("bowler", "yorker_percentage")),
    g("Compare only one player, Kohli.", "unsupported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Virat Kohli"], "comparison_metrics": CORE_BATTER_METRICS}),
    g("Compare Kohli and Unknown Player by strike rate.", "unsupported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Virat Kohli"], "comparison_metrics": ["batting_strike_rate"]}),
    g("Show me the fastest team against Australia.", "unsupported", "aggregate", "team", "batting_strike_rate", ("team",), {"opposition": "Australia"}),
    g("Which team has the best economy against India?", "unsupported", "aggregate", "bowler", "economy_rate", ("team",), {"opposition": "India"}),
    g("Compare Bumrah and Kohli by economy.", "unsupported", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Virat Kohli", "Jasprit Bumrah"], "comparison_metrics": ["economy_rate"]}),
    g("Compare Rohit and Bumrah by strike rate.", "unsupported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Jasprit Bumrah"], "comparison_metrics": ["batting_strike_rate"]}),
    g("Who has the better economy, Starc or Rabada, minimum 9999 legal balls?", "insufficient_evidence", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Mitchell Starc", "Kagiso Rabada"], "comparison_metrics": ["economy_rate"]}),
    g("Compare Kohli and Rohit at Wankhede.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Virat Kohli"], "comparison_metrics": CORE_BATTER_METRICS, "venue": "Wankhede Stadium, Mumbai"}, columns=("player", "batting_strike_rate")),
    g("Compare Bumrah and Starc at the MCG.", "insufficient_evidence", "player_compare", "bowler", "economy_rate", ("bowler",), {"compare_players": ["Jasprit Bumrah", "Mitchell Starc"], "comparison_metrics": CORE_BOWLER_METRICS, "venue": "Melbourne Cricket Ground"}),
    g("Compare Kohli and Rohit against Australia in the powerplay.", "supported", "player_compare", "batter", "batting_strike_rate", ("batter",), {"compare_players": ["Rohit Sharma", "Virat Kohli"], "comparison_metrics": CORE_BATTER_METRICS, "opposition": "Australia", "phase": "powerplay"}, columns=("player", "batting_strike_rate")),
]
